---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  forwardAuth:
    address: http://auth-service.default.svc.cluster.local/auth/traefik
    authResponseHeaders:
      - x-username
      - x-auth-token

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth-routes
spec:
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      priority: 10 # Добавляем маршрут с большим приоритетом, чтобы эти натсройки применились поверх предыдущих
      services:
        - name: echoserver
          namespace: default
          port: 80
      middlewares:
        - name: auth # Включаем forward-auth
          namespace: default
